language: node_js
node_js:
  - "0.10"
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g grunt-cli"
  - "npm install -g meteorite"
  - "cd app && mrt install"
before_script:
  - "mrt --settings settings_test.json"
  - sleep 5
  - "cd .."
services:
  - mongodb
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e51550d6f5099e684b50
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false